INSERT IGNORE INTO specialization (specialization_id,specialization_in) VALUES ('SP001','Cardiologist');
INSERT IGNORE INTO specialization (specialization_id,specialization_in) VALUES ('SP002','Neurologist');
INSERT IGNORE INTO specialization (specialization_id,specialization_in) VALUES ('SP003','Pediatrician');
INSERT IGNORE INTO specialization (specialization_id,specialization_in) VALUES ('SP004','Dermatologist');
INSERT IGNORE INTO specialization (specialization_id,specialization_in) VALUES ('SP005','Orthopedic Surgeon');
INSERT IGNORE INTO specialization (specialization_id,specialization_in) VALUES ('SP006','Ophthalmologist');
INSERT IGNORE INTO specialization (specialization_id,specialization_in) VALUES ('SP007','Psychiatrist');
INSERT IGNORE INTO specialization (specialization_id,specialization_in) VALUES ('SP008','Oncologist');
INSERT IGNORE INTO specialization (specialization_id,specialization_in) VALUES ('SP009','General Practitioner');
INSERT IGNORE INTO specialization (specialization_id,specialization_in) VALUES ('SP010','Gastroenterologist');
