INSERT IGNORE INTO specialization (specialization_in) VALUES ('Cardiologist');
INSERT IGNORE INTO specialization (specialization_in) VALUES ('Neurologist');
INSERT IGNORE INTO specialization (specialization_in) VALUES ('Pediatrician');
INSERT IGNORE INTO specialization (specialization_in) VALUES ('Dermatologist');
INSERT IGNORE INTO specialization (specialization_in) VALUES ('Orthopedic Surgeon');
INSERT IGNORE INTO specialization (specialization_in) VALUES ('Ophthalmologist');
INSERT IGNORE INTO specialization (specialization_in) VALUES ('Psychiatrist');
INSERT IGNORE INTO specialization (specialization_in) VALUES ('Oncologist');
INSERT IGNORE INTO specialization (specialization_in) VALUES ('General Practitioner');
INSERT IGNORE INTO specialization (specialization_in) VALUES ('Gastroenterologist');
