package com.masood.model;

public enum Specilist
{
	 ORTHOPEDICS,
	 INTERNAL_MEDICINE,
	 OBSTETRICS,
	 GYNECOLOGY,
	 DERMATOLOGY,
	 PEDIATRICS,
	 RADIOLOGY,
	 GENERAL_SURGERY,
	 OPHTHALAMOLOGY,
	 CARDIOLOGY,
	 GASTROENTEROLOGY,
	 ONCOLOGY,
	 EMERGENCY_MEDICINE,
	 ANESTHESIOLOGY,
	 UROLOGY,
	 FAMILY_MEDICINE,
	 NEUROLOGY
}
